theme[main_bg]="#121212"

theme[main_fg]="#c0caf5"

theme[title]="#7aa2f7"
theme[hi_fg]="#7aa2f7"

theme[selected_bg]="#1f2335"
theme[selected_fg]="#c0caf5"

theme[inactive_fg]="#565f89"

theme[cpu_box]="#3a405f"
theme[mem_box]="#3a405f"
theme[net_box]="#3a405f"
theme[proc_box]="#3a405f"

theme[div_line]="#2a2f45"

theme[temp_start]="#7fbf7f"
theme[temp_mid]="#c8a15a"
theme[temp_end]="#c4746e"

theme[cpu_start]="#7fbf7f"
theme[cpu_mid]="#c8a15a"
theme[cpu_end]="#c4746e"

theme[free_start]="#7fbf7f"
theme[free_mid]="#77C4E6"
theme[free_end]="#7aa2f7"

theme[cached_start]="#565f89"
theme[cached_mid]="#77C4E6"
theme[cached_end]="#7aa2f7"

theme[available_start]="#77C4E6"
theme[available_mid]="#7aa2f7"
theme[available_end]="#bb9af7"

theme[graph_text]="#7aa2f7"
theme[proc_misc]="#7aa2f7"
