set -g mouse on
set -g mode-keys vi
set -g cursor-style bar
set -g allow-passthrough on

# Keybindings
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"
bind-key c new-window -c "#{pane_current_path}"
bind-key '"' split-window -v -c "#{pane_current_path}"
bind-key % split-window -h -c "#{pane_current_path}"

# Start window numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# Reload config with prefix+r 
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

###### Color Pallette ######

# Catppuccin Mocha color definitions
set -g @catppuccin_bg "#1E1E2E"     # Background
set -g @catppuccin_fg "#CDD6F4"     # Foreground
set -g @catppuccin_yellow "#F9E2AF" # Yellow
set -g @catppuccin_green "#A6E3A1"  # Green
set -g @catppuccin_red "#F38BA8"    # Red
set -g @catppuccin_blue "#89B4FA"   # Blue
set -g @catppuccin_cyan "#94E2D5"   # Cyan
set -g @catppuccin_purple "#CBA6F7" # Purple
set -g @catppuccin_grey "#45475A"   # Grey

###### Status Bar ######

set -g status on
set -g status-position top
set -g status-justify centre
set -g status-interval 5

# Bar colors
set -g status-style "bg=#232430,fg=#7aa2f7"

# Left section
set -g status-left-length 20
set -g status-left "  #[fg=#f7768e,bold]#{session_name}"

# Right section
set -g status-right-length 20
set -g status-right "#[fg=#73daca]%H:%M  "

###### Window styling ######

# Inactive window
setw -g window-status-format "#[fg=#565f89]#I:#W"

# Active window
setw -g window-status-current-format "#[fg=#7aa2f7,bold]#I:#W"

# Window separator
setw -g window-status-separator " • "

###### Additional Styling ######

# Pane border style
setw -g pane-border-style "fg=#414868"
setw -g pane-active-border-style "fg=#7aa2f7"

# Message style
set -g message-style "bg=#232430,fg=#89b4fa"
set -g message-command-style "bg=#232430,fg=#89b4fa"

# Copy mode style
setw -g mode-style "bg=#2a2f45,fg=#c0caf5"
